# Generated by Django 4.2.20 on 2025-05-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=None, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the order was created.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.TextField(help_text="A detailed description of the order."),
        ),
        migrations.AlterField(
            model_name="order",
            name="title",
            field=models.CharField(help_text="The title of the order.", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="The user who placed the order.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                help_text="The age of the user in years."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the user was created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The unique email address of the user.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="The full name of the user.", max_length=255
            ),
        ),
    ]
